version: '3.9'

services:
  server:
    env_file:
      "./server/.env"
    build:
      context: ./server
      dockerfile: ./Dockerfile
    ports:
      - "5000:5000"
  app:
    build:
      context: ./client
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
